/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the profile head
         * @description Never answers 404. A user has exactly one profile, so an account that has none yet gets an empty one created on the spot — the client has no "not created yet" state to carry.
         */
        get: operations["own"];
        /**
         * Replace the profile head
         * @description Requires `If-Match`. A field left out is cleared — this replaces the head rather than patching it. Preferences are not part of it and have their own endpoint.
         */
        put: operations["replace"];
        post?: never;
        /**
         * Delete the profile and everything under it
         * @description Sections, entries, atoms and wordings go with it. The account stays: the next read gives an empty profile back. Requires If-Match — this is the one call that cannot be undone.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace the generation preferences
         * @description Requires `If-Match`. Separate from the head so that editing a headline cannot reset someone's writing style by omission.
         */
        put: operations["replacePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the sections in display order
         * @description Every item carries its own version, so editing one needs no extra read.
         */
        get: operations["listSections"];
        put?: never;
        /** Add a section at the end */
        post: operations["createSection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/sections/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Put the sections in this order
         * @description The list must name every section. A partial one would leave the rest to be guessed; sending all of them also makes the call idempotent.
         */
        post: operations["reorderSections"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entries, optionally within one section */
        get: operations["listEntries"];
        put?: never;
        /** Add an entry at the end of its section */
        post: operations["createEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/entries/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Put one section's entries in this order
         * @description The list must name every entry of that section.
         */
        post: operations["reorderEntries"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/atoms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List atoms with their wordings
         * @description Unpaginated: a profile holds tens to a few hundred atoms and the editor loads all of them (EK D.6.2).
         */
        get: operations["listAtoms"];
        put?: never;
        /**
         * Add an atom and its first wording
         * @description Content is required: an atom with no wording is a fact nobody can read, and nothing downstream can render or measure it.
         */
        post: operations["createAtom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/atoms/{id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a wording
         * @description One wording per language and tone; a second one for the same pair is refused rather than left to a database constraint.
         */
        post: operations["addVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/atoms/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Put one group of atoms in this order
         * @description The atoms of an entry, or the ones hanging straight off a section.
         */
        post: operations["reorderAtoms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a CV against a job posting
         * @description Answers 202 with a job to follow. A generation reads the                     posting with an LLM, scores the whole profile against it,                     then renders and compiles — half a minute is ordinary, and                     a request held open for that long is a request that times                     out somewhere in between.
         *
         *     The preflights are synchronous. A posting that does not                     read as one and a profile with nothing in it are both                     refused here, on the spot, rather than accepted and failed                     thirty seconds later.
         *
         *     `Idempotency-Key` is honoured: the same key from the same                     user answers with the job it already made, so a double                     click produces one CV and not two.
         */
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/sections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a section
         * @description Takes its entries, atoms and variants with it. Requires If-Match, so a section someone else has changed since you read it is not removed on stale information.
         */
        delete: operations["deleteSection"];
        options?: never;
        head?: never;
        /**
         * Change part of a section
         * @description A field left out is left alone. Requires If-Match.
         */
        patch: operations["patchSection"];
        trace?: never;
    };
    "/api/v1/profile/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an entry
         * @description Takes its atoms and their variants with it. Requires If-Match.
         */
        delete: operations["deleteEntry"];
        options?: never;
        head?: never;
        /**
         * Change part of an entry
         * @description A field left out is left alone; a nullable field sent as null is cleared. Requires If-Match.
         */
        patch: operations["patchEntry"];
        trace?: never;
    };
    "/api/v1/profile/atoms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an atom
         * @description Takes its wordings with it.
         */
        delete: operations["deleteAtom"];
        options?: never;
        head?: never;
        /**
         * Change an atom's controls
         * @description Importance, locks, verification and the scoring inputs. Text lives on a wording. Requires If-Match.
         */
        patch: operations["patchAtom"];
        trace?: never;
    };
    "/api/v1/profile/atoms/{id}/variants/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a wording
         * @description Not the last one, and not the primary one while others remain: an atom has to keep a wording, and a default among them.
         */
        delete: operations["deleteVariant"];
        options?: never;
        head?: never;
        /**
         * Change a wording
         * @description Content is optional: making a wording the default is not a text edit and does not need the sentence back. When content is sent it is the whole of it, not a run at a time, and changing the words clears the measured render costs — the same sentence is what made them true. Requires If-Match.
         */
        patch: operations["patchVariant"];
        trace?: never;
    };
    "/api/v1/profile/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the whole profile
         * @description `?format=json` gives a nested copy in the shapes this API already publishes; `?format=markdown` gives the same content to read. Both are served as a download.
         */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Where a job has got to
         * @description `generationId` is present only when the status is `completed`, `error` only when it is `failed`. Both are terminal, and a client may stop polling on either.
         *
         *     Polling this is the supported fallback for a progress stream that closed without a terminal event — a spinner over work that already finished is the one outcome the product refuses to produce.
         */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{jobId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Watch a job as it runs
         * @description A server-sent event stream. Three event names: `phase`                     while it runs, then exactly one of `completed` or                     `failed`, after which the stream closes.
         *
         *     The current state is sent immediately on connect, so a                     client that reconnects is caught up without replay — and a                     job that finished between the 202 and the subscribe sends                     its outcome rather than nothing at all.
         *
         *     `Last-Event-ID` is accepted and not replayed from: ids                     order the events of one stream, and the snapshot on                     connect does the catching up. If the stream ever closes                     without a terminal event, `GET /jobs/{jobId}` is the                     supported way to find out what happened.
         */
        get: operations["stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{generationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One generation and how well it fits the posting
         * @description Carries Faz F's coverage report: how many of the posting's                     required and preferred skills the finished page actually                     says, which ones are missing, and a level over the counts.
         *
         *     **Counts, never a percentage.** Bolum 23.3 forbids one by                     name — the measurement compares skill names, and a figure                     to the decimal place invites the reader to treat it as a                     hiring probability.
         *
         *     The report is measured on the atoms that reached the page,                     not on everything that was ranked, so it never credits a                     skill the document does not claim. A general-mode                     generation has no report at all: there was no posting to                     be relevant to.
         */
        get: operations["read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/{generationId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a generation as a PDF
         * @description Re-rendered from the stored content snapshot, never from                     the profile. Editing a bullet afterwards does not change                     a CV that has already been sent — the document that comes                     back is the one that was made.
         *
         *     No LLM and no scoring: one compilation, and the same                     generation produces the same bytes on any day.
         */
        get: operations["download"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Today's usage against today's limits
         * @description `resetsAt` is an absolute instant, not an hour: the day boundary is UTC and the client writes the sentence in the user's own locale. Counters roll over at UTC midnight, which is 03:00 in Turkey.
         */
        get: operations["usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContactUpdate: {
            name?: string;
            email?: string;
            phone?: string;
            linkedin?: string;
            github?: string;
            website?: string;
            location?: string;
        };
        /** @description Replacement values for the profile head */
        ProfileUpdate: {
            /** @example Backend Engineer */
            headline?: string;
            contact?: components["schemas"]["ContactUpdate"];
            selfDescription?: string;
            /**
             * @description The language the profile is authored in
             * @example en
             */
            sourceLanguage: string;
            /** @description At least one; the first is the working language */
            enabledLanguages: string[];
        };
        Contact: {
            name?: string;
            email?: string;
            phone?: string;
            linkedin?: string;
            github?: string;
            website?: string;
            location?: string;
        };
        Defaults: {
            /** Format: int32 */
            maxPages?: number;
            templateId?: string;
            cvLanguage?: string;
            coverLetterLanguage?: string;
        };
        Preferences: {
            writingStyle?: components["schemas"]["WritingStyle"];
            defaults?: components["schemas"]["Defaults"];
        };
        /** @description The head of the Master Profile */
        Profile: {
            /**
             * @description One line under the name
             * @example Backend Engineer
             */
            headline?: string;
            contact?: components["schemas"]["Contact"];
            /** @description Free text the user writes about themselves */
            selfDescription?: string;
            preferences?: components["schemas"]["Preferences"];
            /**
             * @description The language the profile is authored in
             * @example en
             */
            sourceLanguage?: string;
            /** @description Languages this profile can be rendered in */
            enabledLanguages?: string[];
            /**
             * Format: int32
             * @description How complete the profile is, 0-100
             * @example 0
             */
            completeness?: number;
        };
        WritingStyle: {
            emphasizeMetrics?: boolean;
            /** @enum {string} */
            tone?: "formal" | "casual" | "technical";
            conciseSentences?: boolean;
            customInstructions?: string;
        };
        /** @description RFC 7807 problem detail with a translatable code */
        ApiError: {
            /**
             * @description Relative reference identifying the problem type
             * @example /errors/conflicting-preferences
             */
            type?: string;
            /**
             * @description Developer-facing English, stable across occurrences. Never displayed.
             * @example Conflicting preferences
             */
            title?: string;
            /**
             * Format: int32
             * @description HTTP status
             * @example 409
             */
            status: number;
            /**
             * @description The path that produced it
             * @example /api/v1/generations
             */
            instance?: string;
            /**
             * @description Translation key: the client resolves errors.{CODE}
             * @enum {string}
             */
            code: "INSUFFICIENT_PROFILE" | "UNPARSEABLE_JOB_DESCRIPTION" | "CONFLICTING_PREFERENCES" | "FEATURE_REQUIRES_ACCOUNT" | "QUOTA_EXCEEDED" | "ALL_PROVIDERS_UNAVAILABLE" | "COMPILATION_FAILED" | "PAGE_LIMIT_EXCEEDED" | "REWRITE_VALIDATION_FAILED" | "EMBEDDING_UNAVAILABLE" | "GENERATION_PAUSED" | "PDF_NOT_TEXT_BASED" | "PDF_ENCRYPTED" | "EXTRACTION_EMPTY" | "EXTRACTION_TIMEOUT" | "LANGUAGE_UNDETECTED" | "PROFILE_QUOTA_EXCEEDED" | "ANONYMOUS_SESSION_EXPIRED" | "ATOM_LIMIT_EXCEEDED" | "NO_ANONYMOUS_PROFILE" | "PROFILE_ALREADY_EXISTS" | "GENERATION_ARTIFACT_EXPIRED" | "CSRF_TOKEN_INVALID" | "RESOURCE_NOT_FOUND" | "VERSION_CONFLICT" | "PRECONDITION_REQUIRED" | "VALIDATION_FAILED" | "INTERNAL_ERROR" | "METHOD_NOT_ALLOWED" | "NOT_ACCEPTABLE" | "UNSUPPORTED_MEDIA_TYPE";
            /**
             * @description Values the translated message interpolates. Keys and types are fixed per code; the server refuses to publish anything undeclared.
             * @example {
             *       "pinnedPages": 2.3,
             *       "maxPages": 1
             *     }
             */
            params?: {
                [key: string]: unknown;
            };
            /** @description What the user can do about it. The server owns this list. */
            resolutions?: components["schemas"]["Resolution"][];
        };
        Resolution: {
            /** @enum {string} */
            action?: "increase_page_limit" | "review_pins" | "keep_top_pinned" | "sign_up" | "paste_full_posting" | "continue_as_general_cv" | "continue_anyway" | "switch_to_manual_form" | "complete_profile" | "retry";
            params?: {
                [key: string]: unknown;
            };
        };
        DefaultsUpdate: {
            /** Format: int32 */
            maxPages?: number;
            templateId?: string;
            cvLanguage?: string;
            coverLetterLanguage?: string;
        };
        PreferencesUpdate: {
            writingStyle?: components["schemas"]["WritingStyleUpdate"];
            defaults?: components["schemas"]["DefaultsUpdate"];
        };
        WritingStyleUpdate: {
            emphasizeMetrics?: boolean;
            /** @enum {string} */
            tone?: "formal" | "casual" | "technical";
            conciseSentences?: boolean;
            customInstructions?: string;
        };
        SectionCreate: {
            /** @enum {string} */
            kind: "about" | "education" | "experience" | "projects" | "skills" | "soft_skills" | "languages" | "custom";
            title: string;
            /**
             * @description Defaults to bullet_list
             * @enum {string}
             */
            layout?: "bullet_list" | "entry_list" | "inline_list" | "two_column";
            alwaysInclude?: boolean;
            verbatim?: boolean;
        };
        Section: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            kind?: "about" | "education" | "experience" | "projects" | "skills" | "soft_skills" | "languages" | "custom";
            /**
             * @description The heading as rendered
             * @example Experience
             */
            title?: string;
            /** @enum {string} */
            layout?: "bullet_list" | "entry_list" | "inline_list" | "two_column";
            /**
             * Format: int32
             * @description Position among the sections, from 0
             */
            displayOrder?: number;
            /** @description Selection may not drop it, whatever the budget says */
            alwaysInclude?: boolean;
            /** @description Rendered as written; no rewriting touches it */
            verbatim?: boolean;
            /** @description Inactive sections enter no CV at all */
            active?: boolean;
            /**
             * Format: int64
             * @description Send it back as If-Match on the next write
             * @example 0
             */
            version?: number;
        };
        Reorder: {
            /** @description Every id of the collection, in the order they should appear */
            ids: string[];
        };
        EntryCreate: {
            /** Format: uuid */
            sectionId: string;
            title: string;
            organization?: string;
            location?: string;
            /** Format: date */
            startDate?: string;
            /**
             * Format: date
             * @description Leave out while ongoing
             */
            endDate?: string;
            url?: string;
            /** Format: float */
            importance?: number;
            alwaysInclude?: boolean;
            verbatim?: boolean;
            /**
             * Format: int32
             * @description Defaults to 2
             */
            minAtoms?: number;
        };
        Entry: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            sectionId?: string;
            /** @example Backend Engineer */
            title?: string;
            /** @example Acme */
            organization?: string;
            location?: string;
            /** Format: date */
            startDate?: string;
            /**
             * Format: date
             * @description Absent while ongoing
             */
            endDate?: string;
            url?: string;
            /**
             * Format: int32
             * @description Position within its section, from 0
             */
            displayOrder?: number;
            /**
             * Format: float
             * @description Weight in scoring, 0 to 1
             * @example 0.5
             */
            importance?: number;
            active?: boolean;
            /** @description Selection may not drop it */
            alwaysInclude?: boolean;
            /** @description Never sent for rewriting */
            verbatim?: boolean;
            /**
             * Format: int32
             * @description Below this many atoms the entry is dropped whole (Bolum 20)
             */
            minAtoms?: number;
            /**
             * Format: int64
             * @description Send back as If-Match
             * @example 0
             */
            version?: number;
        };
        EntryReorder: {
            /** Format: uuid */
            sectionId: string;
            /** @description Every entry of that section, in the order they should appear */
            ids: string[];
        };
        AtomCreate: {
            /** Format: uuid */
            sectionId: string;
            /**
             * Format: uuid
             * @description Leave out for an atom that hangs straight off the section
             */
            entryId?: string;
            /** @enum {string} */
            kind: "bullet" | "skill" | "language" | "certification" | "about_paragraph";
            content: components["schemas"]["Content"];
            /**
             * @description Language of this first wording
             * @example en
             */
            language?: string;
            /** Format: float */
            importance?: number;
            alwaysInclude?: boolean;
            verbatim?: boolean;
            skills?: string[];
            metrics?: string[];
            properNouns?: string[];
        };
        /** @description Semantic runs; no format-specific markup */
        Content: {
            /**
             * Format: int32
             * @description Structure version. Server-owned; leave it out when writing.
             * @example 1
             */
            v?: number;
            runs: components["schemas"]["Run"][];
        };
        Run: {
            /**
             * @description The text itself
             * @example ETL
             */
            t: string;
            /**
             * @description Semantic marks: technology, metric, emphasis, link, organization. Unknown marks are kept and rendered as plain text.
             * @example [
             *       "technology"
             *     ]
             */
            m?: string[];
            /** @description Only on a run marked link, and required there */
            href?: string;
        };
        Atom: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            sectionId?: string;
            /**
             * Format: uuid
             * @description Absent when the atom hangs straight off the section
             */
            entryId?: string;
            /** @enum {string} */
            kind?: "bullet" | "skill" | "language" | "certification" | "about_paragraph";
            /** Format: int32 */
            displayOrder?: number;
            /**
             * Format: float
             * @description Weight in scoring, 0 to 1
             * @example 0.5
             */
            importance?: number;
            active?: boolean;
            /** @description Selection may not drop it */
            alwaysInclude?: boolean;
            /** @description Never sent for rewriting */
            verbatim?: boolean;
            /** @description Canonical skill names, used for matching */
            skills?: string[];
            /** @description Numbers a rewrite may not lose */
            metrics?: string[];
            /** @description Names a rewrite may not invent or alter */
            properNouns?: string[];
            /** @enum {string} */
            source?: "manual" | "cv_upload" | "github";
            /** @description The user has confirmed the fact */
            verified?: boolean;
            /** @description Every wording, primary first */
            variants?: components["schemas"]["Variant"][];
            /**
             * Format: int64
             * @description Send back as If-Match
             * @example 0
             */
            version?: number;
        };
        Variant: {
            /** Format: uuid */
            id?: string;
            /** @description The wording used when nothing more specific is asked for */
            primary?: boolean;
            /** @example en */
            language?: string;
            /**
             * @description Absent means the neutral register
             * @enum {string}
             */
            tone?: "formal" | "casual" | "technical";
            content?: components["schemas"]["Content"];
            /** @description The same text with every mark removed */
            plainText?: string;
            /** @description sha256 of the plain text. Re-marking a sentence does not change it, so it is what a 'needs re-measuring' hint should watch. */
            contentHash?: string;
            /**
             * @description Who wrote it
             * @enum {string}
             */
            createdBy?: "user" | "llm_extract" | "llm_translate" | "llm_rewrite";
            /** @description The source has moved on; this wording needs regenerating */
            stale?: boolean;
            /**
             * Format: int64
             * @description Send back as If-Match
             * @example 0
             */
            version?: number;
        };
        VariantWrite: {
            content: components["schemas"]["Content"];
            /** @example en */
            language?: string;
            /**
             * @description Leave out for the neutral register
             * @enum {string}
             */
            tone?: "formal" | "casual" | "technical";
            /** @description Make this the wording used by default */
            primary?: boolean;
        };
        AtomReorder: {
            /** Format: uuid */
            sectionId: string;
            /**
             * Format: uuid
             * @description Leave out to order the section's own atoms
             */
            entryId?: string;
            /** @description Every atom of that group, in order */
            ids: string[];
        };
        /** @description A generation against a job posting */
        GenerationRequest: {
            /** @description The posting, pasted as it was found. Omitted or blank means a general CV: no posting, no LLM. */
            jobDescription?: string;
            /**
             * @description Proceed even though the preflight refused the text
             * @default false
             */
            acknowledgePreflight: boolean;
            /**
             * Format: int32
             * @description How many pages the CV may take
             * @example 1
             */
            maxPages?: number;
            /**
             * @description Which wording to render, as an ISO 639-1 code. Omitted, the profile decides — and its `auto` follows the posting.
             * @example en
             */
            language?: string;
        };
        /** @description A generation that was accepted and queued */
        AcceptedJobResponse: {
            /**
             * Format: uuid
             * @description Follow it at /api/v1/jobs/{jobId}
             */
            jobId?: string;
            /** @enum {string} */
            status?: "queued" | "running" | "completed" | "failed" | "cancelled";
            /**
             * @description Server-sent events for this job
             * @example /api/v1/jobs/9b1c4e7a-.../stream
             */
            streamUrl?: string;
        };
        SectionPatch: {
            /** @enum {string} */
            kind?: "about" | "education" | "experience" | "projects" | "skills" | "soft_skills" | "languages" | "custom";
            title?: string;
            /** @enum {string} */
            layout?: "bullet_list" | "entry_list" | "inline_list" | "two_column";
            alwaysInclude?: boolean;
            verbatim?: boolean;
            active?: boolean;
        };
        EntryPatch: {
            title?: string;
            /** @description Send null to clear */
            organization?: string | null;
            location?: string | null;
            /** Format: date */
            startDate?: string | null;
            /**
             * Format: date
             * @description Send null when the job becomes ongoing again
             */
            endDate?: string | null;
            url?: string | null;
            /** Format: float */
            importance?: number;
            active?: boolean;
            alwaysInclude?: boolean;
            verbatim?: boolean;
            /** Format: int32 */
            minAtoms?: number;
        };
        AtomPatch: {
            /** @enum {string} */
            kind?: "bullet" | "skill" | "language" | "certification" | "about_paragraph";
            /**
             * Format: float
             * @description Weight in scoring, 0 to 1
             */
            importance?: number;
            active?: boolean;
            alwaysInclude?: boolean;
            verbatim?: boolean;
            verified?: boolean;
            /** @description Replaces the whole list */
            skills?: string[];
            metrics?: string[];
            properNouns?: string[];
        };
        VariantPatch: {
            /** @description The replacement wording. Leave it out to change nothing but the fields below. */
            content?: components["schemas"]["Content"];
            /** @example en */
            language?: string;
            /**
             * @description Send null to return the wording to the neutral register
             * @enum {string|null}
             */
            tone?: "formal" | "casual" | "technical" | null;
            /** @description Make this the wording used by default */
            primary?: boolean;
        };
        EntryExport: {
            entry?: components["schemas"]["Entry"];
            atoms?: components["schemas"]["Atom"][];
        };
        /** @description A complete, self-contained copy of a profile */
        ProfileExport: {
            /**
             * Format: date-time
             * @description When this copy was made
             */
            exportedAt?: string;
            profile?: components["schemas"]["Profile"];
            sections?: components["schemas"]["SectionExport"][];
        };
        SectionExport: {
            section?: components["schemas"]["Section"];
            entries?: components["schemas"]["EntryExport"][];
            /** @description Atoms hanging straight off the section */
            atoms?: components["schemas"]["Atom"][];
        };
        /** @description A job's progress or its outcome */
        JobStatusResponse: {
            /** Format: uuid */
            jobId?: string;
            /** @enum {string} */
            status?: "queued" | "running" | "completed" | "failed" | "cancelled";
            phase?: string;
            label?: string;
            /** Format: int32 */
            pct?: number;
            detail?: string;
            /** Format: uuid */
            generationId?: string;
            /** Format: int32 */
            pageCount?: number;
            error?: {
                [key: string]: unknown;
            };
        };
        /** @description How much of the posting's vocabulary the CV actually says. Counts, never a percentage — Bolum 23.3. */
        FitReport: {
            /** Format: int32 */
            requiredCovered?: number;
            /** Format: int32 */
            requiredTotal?: number;
            /** Format: int32 */
            preferredCovered?: number;
            /** Format: int32 */
            preferredTotal?: number;
            /** @description Posting skills the page says, in the posting's own words */
            coveredSkills?: string[];
            missingRequired?: string[];
            missingPreferred?: string[];
            /** @enum {string} */
            level?: "WEAK" | "MODERATE" | "GOOD" | "STRONG";
        };
        /** @description A generation that was made */
        GenerationResponse: {
            /** Format: uuid */
            generationId?: string;
            /** @enum {string} */
            status?: "completed" | "failed" | "superseded";
            /**
             * Format: int32
             * @description How many pages the compiled document came to
             */
            pageCount?: number;
            /** Format: date-time */
            createdAt?: string;
            fitReport?: components["schemas"]["FitReport"];
        };
        /** @description One metric's allowance for today */
        Usage: {
            metric?: string;
            /**
             * Format: int32
             * @description What was actually spent. Never above `limit`, so `used`/`limit` is a pair that can be printed as it is.
             */
            used?: number;
            /**
             * Format: int32
             * @description Every request that took a unit, refusals included. Equal to `used` until the limit is reached, above it afterwards.
             */
            attempted?: number;
            /** Format: int32 */
            limit?: number;
            /**
             * Format: int32
             * @description `limit - used`, never negative
             */
            remaining?: number;
            /**
             * Format: date-time
             * @description When the counters roll over, as an absolute instant. The boundary is UTC midnight.
             */
            resetsAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    own: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile head */
            200: {
                headers: {
                    /** @description Current version as a quoted number, for If-Match on writes. Sent as: "7" */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Unexpected failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    replace: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description The version last read, quoted
                 * @example 7
                 */
                "If-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description The head as it now stands */
            200: {
                headers: {
                    /** @description The new version */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description VALIDATION_FAILED */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT — someone saved first */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED — no If-Match */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replacePreferences: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description The head as it now stands */
            200: {
                headers: {
                    /** @description The new version */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listSections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every section, primary order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"][];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createSection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Current version as a quoted number, for If-Match on writes. Sent as: "7" */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    reorderSections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reorder"];
            };
        };
        responses: {
            /** @description Every section, in the new order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"][];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listEntries: {
        parameters: {
            query?: {
                sectionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every matching entry, in display order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"][];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Current version as a quoted number, for If-Match on writes. Sent as: "7" */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    reorderEntries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryReorder"];
            };
        };
        responses: {
            /** @description That section's entries, in the new order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"][];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listAtoms: {
        parameters: {
            query?: {
                sectionId?: string;
                entryId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every matching atom, in display order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Atom"][];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createAtom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtomCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Current version as a quoted number, for If-Match on writes. Sent as: "7" */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Atom"];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    addVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantWrite"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    /** @description Current version as a quoted number, for If-Match on writes. Sent as: "7" */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Variant"];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    reorderAtoms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtomReorder"];
            };
        };
        responses: {
            /** @description That group's atoms, in the new order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Atom"][];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationRequest"];
            };
        };
        responses: {
            /** @description Queued; follow the Location */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AcceptedJobResponse"];
                };
            };
            /** @description UNPARSEABLE_JOB_DESCRIPTION or INSUFFICIENT_PROFILE */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteSection: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    patchSection: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionPatch"];
            };
        };
        responses: {
            /** @description The section as it now stands */
            200: {
                headers: {
                    /** @description Current version as a quoted number, for If-Match on writes. Sent as: "7" */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteEntry: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    patchEntry: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryPatch"];
            };
        };
        responses: {
            /** @description The entry as it now stands */
            200: {
                headers: {
                    /** @description Current version as a quoted number, for If-Match on writes. Sent as: "7" */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteAtom: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    patchAtom: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtomPatch"];
            };
        };
        responses: {
            /** @description The atom as it now stands */
            200: {
                headers: {
                    /** @description Current version as a quoted number, for If-Match on writes. Sent as: "7" */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Atom"];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteVariant: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
                variantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    patchVariant: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
                variantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantPatch"];
            };
        };
        responses: {
            /** @description The wording as it now stands */
            200: {
                headers: {
                    /** @description Current version as a quoted number, for If-Match on writes. Sent as: "7" */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Variant"];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: {
                /**
                 * @description json or markdown
                 * @example json
                 */
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile as a file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileExport"];
                    "text/markdown": string;
                };
            };
            /** @description VALIDATION_FAILED — unknown format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description No such job, or it belongs to someone else */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description No such job, or it belongs to someone else */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The generation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationResponse"];
                };
            };
            /** @description No such generation, or it belongs to someone else */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    download: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description No such generation, or it belongs to someone else */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description GENERATION_ARTIFACT_EXPIRED — nothing left to re-render */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    usage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Usage"][];
                };
            };
        };
    };
}
