/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the profile head
         * @description Never answers 404. A user has exactly one profile, so an account that has none yet gets an empty one created on the spot — the client has no "not created yet" state to carry.
         */
        get: operations["own"];
        /**
         * Replace the profile head
         * @description Requires `If-Match`. A field left out is cleared — this replaces the head rather than patching it. Preferences are not part of it and have their own endpoint.
         */
        put: operations["replace"];
        post?: never;
        /**
         * Delete the profile and everything under it
         * @description Sections, entries, atoms and wordings go with it. The account stays: the next read gives an empty profile back. Requires If-Match — this is the one call that cannot be undone.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace the generation preferences
         * @description Requires `If-Match`. Separate from the head so that editing a headline cannot reset someone's writing style by omission.
         */
        put: operations["replacePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the sections in display order
         * @description Every item carries its own version, so editing one needs no extra read.
         */
        get: operations["list"];
        put?: never;
        /** Add a section at the end */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/sections/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Put the sections in this order
         * @description The list must name every section. A partial one would leave the rest to be guessed; sending all of them also makes the call idempotent.
         */
        post: operations["reorder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entries, optionally within one section */
        get: operations["list_1"];
        put?: never;
        /** Add an entry at the end of its section */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/entries/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Put one section's entries in this order
         * @description The list must name every entry of that section.
         */
        post: operations["reorder_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/atoms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List atoms with their wordings
         * @description Unpaginated: a profile holds tens to a few hundred atoms and the editor loads all of them (EK D.6.2).
         */
        get: operations["list_2"];
        put?: never;
        /**
         * Add an atom and its first wording
         * @description Content is required: an atom with no wording is a fact nobody can read, and nothing downstream can render or measure it.
         */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/atoms/{id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a wording
         * @description One wording per language and tone; a second one for the same pair is refused rather than left to a database constraint.
         */
        post: operations["addVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/atoms/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Put one group of atoms in this order
         * @description The atoms of an entry, or the ones hanging straight off a section.
         */
        post: operations["reorder_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generations/general": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a general CV as a PDF
         * @description No job description, no LLM: the profile is scored on its own terms, selection fills the page, and the document comes back directly. Synchronous and stored nowhere — a generation resource with a job and a download link arrives in Stage 2.
         *
         *     The page limit is a guarantee. When the compiled document exceeds it the server shrinks the budget and tries again twice; only then does it answer PAGE_LIMIT_EXCEEDED, so retrying the same request unchanged will not help.
         */
        post: operations["generalCv"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/sections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a section
         * @description Takes its entries, atoms and variants with it. Requires If-Match, so a section someone else has changed since you read it is not removed on stale information.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        /**
         * Change part of a section
         * @description A field left out is left alone. Requires If-Match.
         */
        patch: operations["patch"];
        trace?: never;
    };
    "/api/v1/profile/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an entry
         * @description Takes its atoms and their variants with it. Requires If-Match.
         */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        /**
         * Change part of an entry
         * @description A field left out is left alone; a nullable field sent as null is cleared. Requires If-Match.
         */
        patch: operations["patch_1"];
        trace?: never;
    };
    "/api/v1/profile/atoms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an atom
         * @description Takes its wordings with it.
         */
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        /**
         * Change an atom's controls
         * @description Importance, locks, verification and the scoring inputs. Text lives on a wording. Requires If-Match.
         */
        patch: operations["patch_2"];
        trace?: never;
    };
    "/api/v1/profile/atoms/{id}/variants/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a wording
         * @description Not the last one, and not the primary one while others remain: an atom has to keep a wording, and a default among them.
         */
        delete: operations["deleteVariant"];
        options?: never;
        head?: never;
        /**
         * Replace a wording's text
         * @description The whole content, not a run at a time. Changing the words clears the measured render costs, because the same sentence is what made them true. Requires If-Match.
         */
        patch: operations["patchVariant"];
        trace?: never;
    };
    "/api/v1/profile/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the whole profile
         * @description `?format=json` gives a nested copy in the shapes this API already publishes; `?format=markdown` gives the same content to read. Both are served as a download.
         */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContactUpdate: {
            name?: string;
            email?: string;
            phone?: string;
            linkedin?: string;
            github?: string;
            website?: string;
            location?: string;
        };
        /** @description Replacement values for the profile head */
        ProfileUpdate: {
            /** @example Backend Engineer */
            headline?: string;
            contact?: components["schemas"]["ContactUpdate"];
            selfDescription?: string;
            /**
             * @description The language the profile is authored in
             * @example en
             */
            sourceLanguage?: string;
            /** @description At least one; the first is the working language */
            enabledLanguages: string[];
        };
        Contact: {
            name?: string;
            email?: string;
            phone?: string;
            linkedin?: string;
            github?: string;
            website?: string;
            location?: string;
        };
        Defaults: {
            /** Format: int32 */
            maxPages?: number;
            templateId?: string;
            cvLanguage?: string;
            coverLetterLanguage?: string;
        };
        Preferences: {
            writingStyle?: components["schemas"]["WritingStyle"];
            defaults?: components["schemas"]["Defaults"];
        };
        /** @description The head of the Master Profile */
        Profile: {
            /**
             * @description One line under the name
             * @example Backend Engineer
             */
            headline?: string;
            contact?: components["schemas"]["Contact"];
            /** @description Free text the user writes about themselves */
            selfDescription?: string;
            preferences?: components["schemas"]["Preferences"];
            /**
             * @description The language the profile is authored in
             * @example en
             */
            sourceLanguage?: string;
            /** @description Languages this profile can be rendered in */
            enabledLanguages?: string[];
            /**
             * Format: int32
             * @description How complete the profile is, 0-100
             * @example 0
             */
            completeness?: number;
        };
        WritingStyle: {
            emphasizeMetrics?: boolean;
            /** @enum {string} */
            tone?: "formal" | "casual" | "technical";
            conciseSentences?: boolean;
            customInstructions?: string;
        };
        /** @description RFC 7807 problem detail with a translatable code */
        ApiError: {
            /**
             * @description Relative reference identifying the problem type
             * @example /errors/conflicting-preferences
             */
            type?: string;
            /**
             * @description Developer-facing English, stable across occurrences. Never displayed.
             * @example Conflicting preferences
             */
            title?: string;
            /**
             * Format: int32
             * @description HTTP status
             * @example 409
             */
            status?: number;
            /**
             * @description The path that produced it
             * @example /api/v1/generations
             */
            instance?: string;
            /**
             * @description Translation key: the client resolves errors.{CODE}
             * @enum {string}
             */
            code?: "INSUFFICIENT_PROFILE" | "UNPARSEABLE_JOB_DESCRIPTION" | "CONFLICTING_PREFERENCES" | "FEATURE_REQUIRES_ACCOUNT" | "QUOTA_EXCEEDED" | "ALL_PROVIDERS_UNAVAILABLE" | "COMPILATION_FAILED" | "PAGE_LIMIT_EXCEEDED" | "REWRITE_VALIDATION_FAILED" | "EMBEDDING_UNAVAILABLE" | "PDF_NOT_TEXT_BASED" | "PDF_ENCRYPTED" | "EXTRACTION_EMPTY" | "EXTRACTION_TIMEOUT" | "LANGUAGE_UNDETECTED" | "PROFILE_QUOTA_EXCEEDED" | "ANONYMOUS_SESSION_EXPIRED" | "ATOM_LIMIT_EXCEEDED" | "NO_ANONYMOUS_PROFILE" | "PROFILE_ALREADY_EXISTS" | "GENERATION_ARTIFACT_EXPIRED" | "CSRF_TOKEN_INVALID" | "RESOURCE_NOT_FOUND" | "VERSION_CONFLICT" | "PRECONDITION_REQUIRED" | "VALIDATION_FAILED" | "INTERNAL_ERROR";
            /**
             * @description Values the translated message interpolates. Keys and types are fixed per code; the server refuses to publish anything undeclared.
             * @example {
             *       "pinnedPages": 2.3,
             *       "maxPages": 1
             *     }
             */
            params?: {
                [key: string]: unknown;
            };
            /** @description What the user can do about it. The server owns this list. */
            resolutions?: components["schemas"]["Resolution"][];
        };
        Resolution: {
            /** @enum {string} */
            action?: "increase_page_limit" | "review_pins" | "keep_top_pinned" | "sign_up" | "paste_full_posting" | "continue_as_general_cv" | "switch_to_manual_form" | "complete_profile" | "retry";
            params?: {
                [key: string]: unknown;
            };
        };
        DefaultsUpdate: {
            /** Format: int32 */
            maxPages?: number;
            templateId?: string;
            cvLanguage?: string;
            coverLetterLanguage?: string;
        };
        PreferencesUpdate: {
            writingStyle?: components["schemas"]["WritingStyleUpdate"];
            defaults?: components["schemas"]["DefaultsUpdate"];
        };
        WritingStyleUpdate: {
            emphasizeMetrics?: boolean;
            /** @enum {string} */
            tone?: "formal" | "casual" | "technical";
            conciseSentences?: boolean;
            customInstructions?: string;
        };
        SectionCreate: {
            /** @enum {string} */
            kind: "about" | "education" | "experience" | "projects" | "skills" | "soft_skills" | "languages" | "custom";
            title: string;
            /**
             * @description Defaults to bullet_list
             * @enum {string}
             */
            layout?: "bullet_list" | "entry_list" | "inline_list" | "two_column";
            alwaysInclude?: boolean;
            verbatim?: boolean;
        };
        Section: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            kind?: "about" | "education" | "experience" | "projects" | "skills" | "soft_skills" | "languages" | "custom";
            /**
             * @description The heading as rendered
             * @example Experience
             */
            title?: string;
            /** @enum {string} */
            layout?: "bullet_list" | "entry_list" | "inline_list" | "two_column";
            /**
             * Format: int32
             * @description Position among the sections, from 0
             */
            displayOrder?: number;
            /** @description Selection may not drop it, whatever the budget says */
            alwaysInclude?: boolean;
            /** @description Rendered as written; no rewriting touches it */
            verbatim?: boolean;
            /** @description Inactive sections enter no CV at all */
            active?: boolean;
            /**
             * Format: int64
             * @description Send it back as If-Match on the next write
             * @example 0
             */
            version?: number;
        };
        Reorder: {
            /** @description Every id of the collection, in the order they should appear */
            ids: string[];
        };
        EntryCreate: {
            /** Format: uuid */
            sectionId: string;
            title: string;
            organization?: string;
            location?: string;
            /** Format: date */
            startDate?: string;
            /**
             * Format: date
             * @description Leave out while ongoing
             */
            endDate?: string;
            url?: string;
            /** Format: float */
            importance?: number;
            alwaysInclude?: boolean;
            verbatim?: boolean;
            /**
             * Format: int32
             * @description Defaults to 2
             */
            minAtoms?: number;
        };
        Entry: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            sectionId?: string;
            /** @example Backend Engineer */
            title?: string;
            /** @example Acme */
            organization?: string;
            location?: string;
            /** Format: date */
            startDate?: string;
            /**
             * Format: date
             * @description Absent while ongoing
             */
            endDate?: string;
            url?: string;
            /**
             * Format: int32
             * @description Position within its section, from 0
             */
            displayOrder?: number;
            /**
             * Format: float
             * @description Weight in scoring, 0 to 1
             * @example 0.5
             */
            importance?: number;
            active?: boolean;
            /** @description Selection may not drop it */
            alwaysInclude?: boolean;
            /** @description Never sent for rewriting */
            verbatim?: boolean;
            /**
             * Format: int32
             * @description Below this many atoms the entry is dropped whole (Bolum 20)
             */
            minAtoms?: number;
            /**
             * Format: int64
             * @description Send back as If-Match
             * @example 0
             */
            version?: number;
        };
        EntryReorder: {
            /** Format: uuid */
            sectionId: string;
            /** @description Every entry of that section, in the order they should appear */
            ids: string[];
        };
        AtomCreate: {
            /** Format: uuid */
            sectionId: string;
            /**
             * Format: uuid
             * @description Leave out for an atom that hangs straight off the section
             */
            entryId?: string;
            /** @enum {string} */
            kind: "bullet" | "skill" | "language" | "certification" | "about_paragraph";
            content: components["schemas"]["Content"];
            /**
             * @description Language of this first wording
             * @example en
             */
            language?: string;
            /** Format: float */
            importance?: number;
            alwaysInclude?: boolean;
            verbatim?: boolean;
            skills?: string[];
            metrics?: string[];
            properNouns?: string[];
        };
        /** @description Semantic runs; no format-specific markup */
        Content: {
            /**
             * Format: int32
             * @description Structure version. Server-owned; leave it out when writing.
             * @example 1
             */
            v?: number;
            runs: components["schemas"]["Run"][];
        };
        Run: {
            /**
             * @description The text itself
             * @example ETL
             */
            t: string;
            /**
             * @description Semantic marks: technology, metric, emphasis, link, organization. Unknown marks are kept and rendered as plain text.
             * @example [
             *       "technology"
             *     ]
             */
            m?: string[];
            /** @description Only on a run marked link, and required there */
            href?: string;
        };
        Atom: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            sectionId?: string;
            /**
             * Format: uuid
             * @description Absent when the atom hangs straight off the section
             */
            entryId?: string;
            /** @enum {string} */
            kind?: "bullet" | "skill" | "language" | "certification" | "about_paragraph";
            /** Format: int32 */
            displayOrder?: number;
            /**
             * Format: float
             * @description Weight in scoring, 0 to 1
             * @example 0.5
             */
            importance?: number;
            active?: boolean;
            /** @description Selection may not drop it */
            alwaysInclude?: boolean;
            /** @description Never sent for rewriting */
            verbatim?: boolean;
            /** @description Canonical skill names, used for matching */
            skills?: string[];
            /** @description Numbers a rewrite may not lose */
            metrics?: string[];
            /** @description Names a rewrite may not invent or alter */
            properNouns?: string[];
            /** @enum {string} */
            source?: "manual" | "cv_upload" | "github";
            /** @description The user has confirmed the fact */
            verified?: boolean;
            /** @description Every wording, primary first */
            variants?: components["schemas"]["Variant"][];
            /**
             * Format: int64
             * @description Send back as If-Match
             * @example 0
             */
            version?: number;
        };
        Variant: {
            /** Format: uuid */
            id?: string;
            /** @description The wording used when nothing more specific is asked for */
            primary?: boolean;
            /** @example en */
            language?: string;
            /**
             * @description Absent means the neutral register
             * @enum {string}
             */
            tone?: "formal" | "casual" | "technical";
            content?: components["schemas"]["Content"];
            /** @description The same text with every mark removed */
            plainText?: string;
            /** @description sha256 of the plain text. Re-marking a sentence does not change it, so it is what a 'needs re-measuring' hint should watch. */
            contentHash?: string;
            /**
             * @description Who wrote it
             * @enum {string}
             */
            createdBy?: "user" | "llm_extract" | "llm_translate" | "llm_rewrite";
            /** @description The source has moved on; this wording needs regenerating */
            stale?: boolean;
            /**
             * Format: int64
             * @description Send back as If-Match
             * @example 0
             */
            version?: number;
        };
        VariantWrite: {
            content: components["schemas"]["Content"];
            /** @example en */
            language?: string;
            /**
             * @description Leave out for the neutral register
             * @enum {string}
             */
            tone?: "formal" | "casual" | "technical";
            /** @description Make this the wording used by default */
            primary?: boolean;
        };
        AtomReorder: {
            /** Format: uuid */
            sectionId: string;
            /**
             * Format: uuid
             * @description Leave out to order the section's own atoms
             */
            entryId?: string;
            /** @description Every atom of that group, in order */
            ids: string[];
        };
        /** @description Overrides for a general CV. Anything omitted follows the profile. */
        GeneralCvRequest: {
            /**
             * Format: int32
             * @description How many pages the CV may take
             * @example 1
             */
            maxPages?: number;
            /**
             * @description Which wording to render, as an ISO 639-1 code
             * @example en
             */
            language?: string;
        };
        SectionPatch: {
            /** @enum {string} */
            kind?: "about" | "education" | "experience" | "projects" | "skills" | "soft_skills" | "languages" | "custom";
            title?: string;
            /** @enum {string} */
            layout?: "bullet_list" | "entry_list" | "inline_list" | "two_column";
            alwaysInclude?: boolean;
            verbatim?: boolean;
            active?: boolean;
        };
        EntryPatch: {
            title?: string;
            /** @description Send null to clear */
            organization?: string;
            location?: string;
            /** Format: date */
            startDate?: string;
            /**
             * Format: date
             * @description Send null when the job becomes ongoing again
             */
            endDate?: string;
            url?: string;
            /** Format: float */
            importance?: number;
            active?: boolean;
            alwaysInclude?: boolean;
            verbatim?: boolean;
            /** Format: int32 */
            minAtoms?: number;
        };
        AtomPatch: {
            /** @enum {string} */
            kind?: "bullet" | "skill" | "language" | "certification" | "about_paragraph";
            /**
             * Format: float
             * @description Weight in scoring, 0 to 1
             */
            importance?: number;
            active?: boolean;
            alwaysInclude?: boolean;
            verbatim?: boolean;
            verified?: boolean;
            /** @description Replaces the whole list */
            skills?: string[];
            metrics?: string[];
            properNouns?: string[];
        };
        EntryExport: {
            entry?: components["schemas"]["Entry"];
            atoms?: components["schemas"]["Atom"][];
        };
        /** @description A complete, self-contained copy of a profile */
        ProfileExport: {
            /**
             * Format: date-time
             * @description When this copy was made
             */
            exportedAt?: string;
            profile?: components["schemas"]["Profile"];
            sections?: components["schemas"]["SectionExport"][];
        };
        SectionExport: {
            section?: components["schemas"]["Section"];
            entries?: components["schemas"]["EntryExport"][];
            /** @description Atoms hanging straight off the section */
            atoms?: components["schemas"]["Atom"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    own: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile head */
            200: {
                headers: {
                    /** @description Current version as a quoted number, for If-Match on writes. Sent as: "7" */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Unexpected failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    replace: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description The version last read, quoted
                 * @example 7
                 */
                "If-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description The head as it now stands */
            200: {
                headers: {
                    /** @description The new version */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description VALIDATION_FAILED */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT — someone saved first */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED — no If-Match */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replacePreferences: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesUpdate"];
            };
        };
        responses: {
            /** @description The head as it now stands */
            200: {
                headers: {
                    /** @description The new version */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    reorder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reorder"];
            };
        };
        responses: {
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                sectionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entry"];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    reorder_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryReorder"];
            };
        };
        responses: {
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                sectionId?: string;
                entryId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtomCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Atom"];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    addVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantWrite"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Variant"];
                };
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    reorder_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtomReorder"];
            };
        };
        responses: {
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    generalCv: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GeneralCvRequest"];
            };
        };
        responses: {
            /** @description The document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description CONFLICTING_PREFERENCES */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description INSUFFICIENT_PROFILE or PAGE_LIMIT_EXCEEDED */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description COMPILATION_FAILED */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SectionPatch"];
            };
        };
        responses: {
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    patch_1: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryPatch"];
            };
        };
        responses: {
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    patch_2: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtomPatch"];
            };
        };
        responses: {
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    deleteVariant: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
                variantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    patchVariant: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string;
            };
            path: {
                id: string;
                variantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantWrite"];
            };
        };
        responses: {
            /** @description RESOURCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description VERSION_CONFLICT */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
            /** @description PRECONDITION_REQUIRED */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: {
                /**
                 * @description json or markdown
                 * @example json
                 */
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile as a file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileExport"];
                };
            };
            /** @description VALIDATION_FAILED — unknown format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
